name: GlobalAuctions
version: 0.5
description:
author: Chaoscrasher & Rise
main: com.jb1services.mc.rise.globalauctions.main.GlobalAuctionsPlugin
api-version: 1.14

commands:
  gas:
    description: Allows you to interact with GlobalAuctions!
    usage: /gas show [auctionid | pname], make [price]
